spring:
	profile:
	active:
	- dev
---
spring:
	prfile: dev     #开发环境
	application:
		name: springclod-config-atguigu-dev
---
spring:
	profile:test    #测试环境
	application:
		name: springclod-config-atguigu-test

# 请保存为UTF-8格式